### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by jishenghuang** [wangjk666/PyDeepFakeDet#1]
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Excuse me, how to solve this error.

**Comment by wangjk666** [comment]
Usually, this error is caused by specifying the wrong GPU number, e.g., if there is only one GPU and the program uses GPUs:1
