### ISSUE TITLE
'EfficientNet' object has no attribute 'extract_textures'

### ISSUE THREAD

**Issue by Kidleyh** [wangjk666/PyDeepFakeDet#7]
Hey , I compared the code with your other repository "m2tr", I found that your deleted the `def extract_textures` in efficientnet.py, and this caused the code to report an error —— 'EfficientNet' object has no attribute 'extract_textures'

**Comment by Kidleyh** [comment]
And It still doesn't work after I complete the `def extract_textures`
File "PyDeepFakeDet/PyDeepFakeDet/models/m2tr.py", line 291, in forward
    features = self.model.extract_features(rgb, layers)
File "PyDeepFakeDet/PyDeepFakeDet/models/efficientnet.py", line 477, in extract_features
    x = self._swish(self._bn0(self._conv_stem(x)))
  File "/anaconda3/envs/DFDet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/PyDeepFakeDet/PyDeepFakeDet/models/efficientnet.py", line 359, in forward
    x = F.conv2d(
RuntimeError: Given groups=1, weight of size [48, 3, 3, 3], expected input[4, 32, 81, 81] to have 3 channels, but got 32 channels instead

**Comment by zhangchaosd** [comment]
Hi, @Kidleyh 

Thank you very much for pointing out this issue. We had found this problem and should have fixed it. Please pull the latest code and check.

Best regards

**Comment by Kidleyh** [comment]
Thank you, I have pulled the latest code and can run m2tr successfully
